version: '3'
services:
  cmimc:
    build: .
    depends_on:
      - mariadb
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - RDS_HOSTNAME=${DOCKER_RDS_HOSTNAME}
      - RDS_PORT=3306
      - RDS_DB_NAME=cmimc
      - RDS_USERNAME=${DOCKER_RDS_USERNAME}
      - RDS_PASSWORD=${DOCKER_RDS_PASSWORD}
      - DEBUG=true

