# Generated by Django 3.1.7 on 2021-11-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0103_contest_is_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tnc_signature',
            field=models.CharField(blank=True, help_text='signature from signing conditions', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'CMU Student'), ('ML', 'Contestant'), ('CO', 'Coach')], default='ML', max_length=2),
        ),
    ]
