# Generated by Django 3.1.7 on 2021-11-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0103_contest_is_math'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampair',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'CMU Student'), ('ML', 'Contestant'), ('CO', 'Coach')], default='ML', max_length=2),
        ),
    ]
