# Generated by Django 3.1.7 on 2021-11-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_auto_20211111_1424'),
        ('website', '0104_auto_20211106_1719'),
    ]

    operations = [
    ]
