# Generated by Django 3.2.9 on 2021-12-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0105_merge_20211111_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('contest', 'name')},
        ),
    ]
