# Generated by Django 3.2.12 on 2022-02-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0106_auto_20211223_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='end_time',
            new_name='fake_end_time',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='start_time',
            new_name='fake_start_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, help_text='preferred name', max_length=100, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='full name', max_length=300, verbose_name='full name'),
        ),
    ]
