# Generated by Django 3.2.12 on 2022-02-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0108_rename_has_started_exam_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='real_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
