# Generated by Django 3.2.12 on 2022-02-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_exam_real_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
