# Generated by Django 3.2.12 on 2022-02-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0114_auto_20220224_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='short_name',
        ),
    ]
