# Generated by Django 3.2.12 on 2022-03-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0107_auto_20220317_1407'),
        ('website', '0115_remove_problem_short_name'),
    ]

    operations = [
    ]
