# Generated by Django 3.2.12 on 2022-03-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0116_merge_20220317_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
