# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\"\x1c\n\x08Password\x12\x10\n\x08password\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\",\n\x0c\x43\x61pabilities\x12\x0e\n\x06memory\x18\x01 \x01(\x04\x12\x0c\n\x04\x63pus\x18\x02 \x01(\x04\"4\n\x0eGradeOperation\x12\x13\n\x0bpython_code\x18\x01 \x01(\x0c\x12\r\n\x05input\x18\x02 \x01(\x0c\"P\n\x0cGradeRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x17\n\x0ftimeout_seconds\x18\x02 \x01(\x01\x12\x1b\n\x02op\x18\x03 \x01(\x0b\x32\x0f.GradeOperation\"P\n\rGradeResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06output\x18\x02 \x01(\x0c\x12\x0f\n\x07summary\x18\x03 \x01(\x0c\x12\x12\n\nplayerlogs\x18\x04 \x01(\x0c\x32[\n\x0b\x43oordinator\x12*\n\x05Serve\x12\x0e.GradeResponse\x1a\r.GradeRequest(\x01\x30\x01\x12 \n\x0bSetPassword\x12\t.Password\x1a\x06.Emptyb\x06proto3')



_PASSWORD = DESCRIPTOR.message_types_by_name['Password']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CAPABILITIES = DESCRIPTOR.message_types_by_name['Capabilities']
_GRADEOPERATION = DESCRIPTOR.message_types_by_name['GradeOperation']
_GRADEREQUEST = DESCRIPTOR.message_types_by_name['GradeRequest']
_GRADERESPONSE = DESCRIPTOR.message_types_by_name['GradeResponse']
Password = _reflection.GeneratedProtocolMessageType('Password', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORD,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:Password)
  })
_sym_db.RegisterMessage(Password)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Capabilities = _reflection.GeneratedProtocolMessageType('Capabilities', (_message.Message,), {
  'DESCRIPTOR' : _CAPABILITIES,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:Capabilities)
  })
_sym_db.RegisterMessage(Capabilities)

GradeOperation = _reflection.GeneratedProtocolMessageType('GradeOperation', (_message.Message,), {
  'DESCRIPTOR' : _GRADEOPERATION,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:GradeOperation)
  })
_sym_db.RegisterMessage(GradeOperation)

GradeRequest = _reflection.GeneratedProtocolMessageType('GradeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRADEREQUEST,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:GradeRequest)
  })
_sym_db.RegisterMessage(GradeRequest)

GradeResponse = _reflection.GeneratedProtocolMessageType('GradeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRADERESPONSE,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:GradeResponse)
  })
_sym_db.RegisterMessage(GradeResponse)

_COORDINATOR = DESCRIPTOR.services_by_name['Coordinator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PASSWORD._serialized_start=21
  _PASSWORD._serialized_end=49
  _EMPTY._serialized_start=51
  _EMPTY._serialized_end=58
  _CAPABILITIES._serialized_start=60
  _CAPABILITIES._serialized_end=104
  _GRADEOPERATION._serialized_start=106
  _GRADEOPERATION._serialized_end=158
  _GRADEREQUEST._serialized_start=160
  _GRADEREQUEST._serialized_end=240
  _GRADERESPONSE._serialized_start=242
  _GRADERESPONSE._serialized_end=322
  _COORDINATOR._serialized_start=324
  _COORDINATOR._serialized_end=415
# @@protoc_insertion_point(module_scope)
